### Recuperar información del pokemon ditto
GET http://localhost:1108/pokemon/ditto

### Serve image
GET http://localhost:1108/image

### Para crear un Pokemon
POST http://localhost:1108/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": [
      "transform"
  ]
}